version: "3.9"

services:
  server:
    build: ./server
    container_name: rpc_server
    ports:
      - "8000:8000"   # exp√µe para host, se quiser testar fora do cliente
    networks:
      - rpc_net
    volumes:
      - rpc_shared:/shared

  client:
    build: ./client
    container_name: rpc_client
    depends_on:
      - server
      - monitor
    networks:
      - rpc_net
    stdin_open: true
    tty: true
    volumes:
      - rpc_shared:/shared

  monitor:
    build: ./monitor
    container_name: rpc_monitor
    ports:
      - "5000:5000"
    networks:
      - rpc_net
    volumes:
      - rpc_shared:/shared
    environment:
      # Clear monitor's events.log on start (default enabled). Set to '0' to keep.
      - RPC_CLEAR_ON_START=1
      # By default deduplication is enabled (remove identical client/server events).
      # Set to '1' to disable deduplication for debugging.
      - RPC_DISABLE_DEDUP=0

networks:
  rpc_net:
    driver: bridge

volumes:
  rpc_shared:
    driver: local